name: minehost-project # <--- Définit le nom du projet Compose

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    networks:
      - minehost-network
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DB_USERNAME=${MYSQL_DB_USERNAME}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    # Ajout du Healthcheck pour vérifier que MySQL est prêt
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", '${MYSQL_DB_USERNAME}', '-p${MYSQL_DB_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  minehost:
    build: 

      context: .
      dockerfile: ./backend/Dockerfile
    container_name: minehost
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - minehost-network
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      - NGROK_TOKEN=${NGROK_TOKEN}
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ./mondes:/home/fuentesr/mondes
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  minehost-network:
    driver: bridge

volumes:
  mysql_data: